<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Saucedemo_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7bf52d1e-0ed4-410d-a3d3-0a0089e3e0fd</testSuiteGuid>
   <testCaseLink>
      <guid>e291c481-507d-4c61-a728-6ef43fc79993</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day-3/Saucedemo/Saucedemo_Login_Data</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e1ed49b7-cfe1-4327-b168-eb1bc9f57622</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Driven_Testing</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e1ed49b7-cfe1-4327-b168-eb1bc9f57622</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>64c54232-2bd9-4536-8c35-3ce4e05e7706</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e1ed49b7-cfe1-4327-b168-eb1bc9f57622</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>bf9ddb67-7640-40c6-b409-816432139c2e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
