<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Please check this box if youd like to_15e628</name>
   <tag></tag>
   <elementGuidId>0a90d65c-d75a-4bd7-9d5c-09e99da52c3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LblmktoCheckbox_36497_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='mktoForm_3124']/div[10]/div/div[2]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2c7322d4-6e6f-4489-ba48-323643e6beb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>mktoCheckbox_36497_0</value>
      <webElementGuid>59ce1b8f-408b-4b36-9003-1949ecdc20d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LblmktoCheckbox_36497_0</value>
      <webElementGuid>85c548b7-d8be-4600-af14-7297d6014ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please check this box if you’d like to receive information about Sauce Labs products, services, and future events. For more information please refer to the Sauce Labs Privacy Policy. You may withdraw your consent at any time.</value>
      <webElementGuid>0664c132-1921-49c3-8e7c-78d9df32d5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LblmktoCheckbox_36497_0&quot;)</value>
      <webElementGuid>7d78edc7-89e5-41d0-b8ad-8fcd91f26b81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='LblmktoCheckbox_36497_0']</value>
      <webElementGuid>e742591b-ebac-44a7-bf24-567ae3165253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mktoForm_3124']/div[10]/div/div[2]/div[2]/label</value>
      <webElementGuid>40c761a0-0ea8-43e5-bd7d-955980c4d6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::label[1]</value>
      <webElementGuid>1f6e482b-f120-4053-a3fa-2947f8153d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::label[2]</value>
      <webElementGuid>b2376554-cf60-411e-9519-a115d319e9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::label[1]</value>
      <webElementGuid>a3bfcf10-5f76-4b25-b8a1-2a9d6dfdb81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please check this box if you’d like to receive information about Sauce Labs products, services, and future events. For more information please refer to the Sauce Labs']/parent::*</value>
      <webElementGuid>9a5cc018-0baa-4fcc-a74f-3899c76d078e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/div[2]/label</value>
      <webElementGuid>d543bef7-7863-4074-b64e-24c781fbc020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'LblmktoCheckbox_36497_0' and (text() = 'Please check this box if you’d like to receive information about Sauce Labs products, services, and future events. For more information please refer to the Sauce Labs Privacy Policy. You may withdraw your consent at any time.' or . = 'Please check this box if you’d like to receive information about Sauce Labs products, services, and future events. For more information please refer to the Sauce Labs Privacy Policy. You may withdraw your consent at any time.')]</value>
      <webElementGuid>8b86e258-95b1-44a8-83e8-65dce0cacce8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
