<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Sales_Contact_Comments__c</name>
   <tag></tag>
   <elementGuidId>d9d2cd1f-5f74-41eb-a320-1f14bac75365</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Sales_Contact_Comments__c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Sales_Contact_Comments__c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>438ccb83-96ef-4466-bc18-5468fcbb8af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Sales_Contact_Comments__c</value>
      <webElementGuid>c6bf7dd2-fcfc-4098-a922-0a9351db36b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sales_Contact_Comments__c</value>
      <webElementGuid>396f5b87-8496-405f-897e-4ad532955597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7ab1493d-9d84-4bfa-be56-e9af2c785014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>LblSales_Contact_Comments__c InstructSales_Contact_Comments__c</value>
      <webElementGuid>a597fe92-1691-43f6-ba9c-399f7def8ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mktoField mktoHasWidth mktoValid</value>
      <webElementGuid>684cd8ad-c168-4b9e-afe4-315f32f75cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32768</value>
      <webElementGuid>bab65642-1804-45b0-bc9a-275f1abca1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e1303ae-40c7-49d7-83c1-b5671736fcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Sales_Contact_Comments__c&quot;)</value>
      <webElementGuid>52b1723a-bbd7-40d9-a3b8-ca8b5d9b7f12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Sales_Contact_Comments__c']</value>
      <webElementGuid>ee6679c8-7486-43f7-9770-611b45b0a259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mktoForm_3124']/div[9]/div/div[2]/textarea</value>
      <webElementGuid>c294f668-5458-4e3b-980d-f832dc758a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3c6b0751-1f8c-40bd-9cb1-6a1d6dcaded6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Sales_Contact_Comments__c' and @name = 'Sales_Contact_Comments__c']</value>
      <webElementGuid>ca54135b-9a98-41ce-a0a1-7dba2558b3df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
