<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Company</name>
   <tag></tag>
   <elementGuidId>2048a69c-d0d8-4d85-aeb6-faf6a601d722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Company</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31b2c0c9-7751-42ec-95cf-401b0ea63539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>214b57bc-17a8-4cb1-b5e9-929127a537f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>d48f2c27-1beb-4ab2-b8e5-a415bf6424bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>6523f7a4-132f-40a2-8b2f-b3677636f1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>LblCompany InstructCompany</value>
      <webElementGuid>bf88d7c3-3e9b-4ddf-9184-0ed571fa7c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b70b0d69-57cc-4f03-b57e-580a84c6c0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mktoField mktoTextField mktoHasWidth mktoRequired</value>
      <webElementGuid>c5bb8d66-3ceb-4e42-b935-e98a9884a1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f299c712-0b54-417f-8a98-7e4bcdf565c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Company&quot;)</value>
      <webElementGuid>dc8ef3aa-7c3b-4de6-85da-93e7b55f9ae5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Company']</value>
      <webElementGuid>7c911b67-caef-4ddf-833d-c80a4f19cbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mktoForm_3124']/div[5]/div/div[2]/input</value>
      <webElementGuid>cca25323-4bdd-4be9-9cd4-033179bbd101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>dce1bbce-8da6-48d5-828b-aaaea36f50b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Company' and @name = 'Company' and @type = 'text']</value>
      <webElementGuid>187738aa-7233-42fb-8d4e-a5a61a7bd06d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
