<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select.Sauce Cross-BrowserSauce Mobi_6b7086</name>
   <tag></tag>
   <elementGuidId>5fb6e650-a09e-469e-94a2-fa0a6f8631f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Solution_Interest__c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Solution_Interest__c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2a6bef07-254f-41f1-a12f-79fa8b379c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Solution_Interest__c</value>
      <webElementGuid>1224fe63-c0dd-4a95-8d2b-48f2a7262b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Solution_Interest__c</value>
      <webElementGuid>fdd27b7c-c553-4990-964d-4093ede784fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>LblSolution_Interest__c InstructSolution_Interest__c</value>
      <webElementGuid>b2511ba9-e0d8-49a0-a202-f7d0eddfbe19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mktoField mktoHasWidth mktoRequired</value>
      <webElementGuid>837f70b8-4bc1-4c03-a6d7-b8780ecb9902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bb2ca886-c754-42cd-8b0e-39e84b4c7da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select...Sauce Cross-BrowserSauce Mobile Sauce Low Code Sauce Error ReportingSauce API QualitySauce VisualSauce Orchestrate </value>
      <webElementGuid>ccf52543-a980-4fb5-8929-79704802bd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Solution_Interest__c&quot;)</value>
      <webElementGuid>d6413f36-4a8d-4603-a85c-82cdd06d9235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Solution_Interest__c']</value>
      <webElementGuid>71b23d9a-b656-478c-b54d-18ba656f87a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mktoForm_3124']/div[8]/div/div[2]/select</value>
      <webElementGuid>5f8be929-a242-43e4-8d72-c995a9ea92d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>c8b98a68-e60f-45b5-b5d9-11361ea703c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[1]</value>
      <webElementGuid>73f010cb-bd72-4a87-af02-9de4ab694e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/select</value>
      <webElementGuid>ce92c0ab-64f9-4dd8-8c78-e50cdf767645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Solution_Interest__c' and @name = 'Solution_Interest__c' and (text() = 'Select...Sauce Cross-BrowserSauce Mobile Sauce Low Code Sauce Error ReportingSauce API QualitySauce VisualSauce Orchestrate ' or . = 'Select...Sauce Cross-BrowserSauce Mobile Sauce Low Code Sauce Error ReportingSauce API QualitySauce VisualSauce Orchestrate ')]</value>
      <webElementGuid>d53ed952-e6f8-4cfa-b17f-5f26e7586452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
