<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alert with OK</name>
   <tag></tag>
   <elementGuidId>804473ec-2bf3-4f70-a703-6397062c739b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Alert with OK')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.analystic</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8dc2df03-3d06-48a7-933e-bd66f5396101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#OKTab</value>
      <webElementGuid>8d9e19d5-61ae-45cd-b399-b8e752789174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>555e8c28-95dd-415a-bd97-9310377884d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>analystic</value>
      <webElementGuid>d9a6105e-d42a-40ca-b4cc-02977ed8756b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alert with OK </value>
      <webElementGuid>cd1898e7-f891-4cfc-a570-9f56159c5975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;nav nav-tabs&quot;]/div[@class=&quot;tabpane pullleft&quot;]/ul[@class=&quot;nav nav-tabs nav-stacked&quot;]/li[@class=&quot;active&quot;]/a[@class=&quot;analystic&quot;]</value>
      <webElementGuid>3e86eebc-9d68-4479-be7f-b981d6f25d27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Alert with OK')]</value>
      <webElementGuid>99982b07-96f9-4579-9259-c73f3ac44b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Site'])[1]/following::a[1]</value>
      <webElementGuid>a8492c15-02ea-40c0-a0a3-b19313633413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ProgressBar'])[1]/following::a[2]</value>
      <webElementGuid>ee2d7a03-267b-4e2a-90ac-ba1de58a7dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert with OK &amp; Cancel'])[1]/preceding::a[1]</value>
      <webElementGuid>a2696c53-9960-4a78-bb30-4be4ae1a089c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert with Textbox'])[1]/preceding::a[2]</value>
      <webElementGuid>bafcb1ad-f417-4cc1-8484-bb191adc500f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alert with OK']/parent::*</value>
      <webElementGuid>aeb02118-328a-432d-8ccd-1bf0a897f48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#OKTab')]</value>
      <webElementGuid>58d68f25-27c6-4ef7-a902-e26653e041d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li/a</value>
      <webElementGuid>900a0f47-bb1e-43d1-9f96-2be28d13e447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#OKTab' and (text() = 'Alert with OK ' or . = 'Alert with OK ')]</value>
      <webElementGuid>e1b574d5-4680-49b7-b844-ee3af2941fe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
